# Generated by Django 3.2.7 on 2021-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery')], max_length=100, null=True),
        ),
    ]
